//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thi63TTQL1_63132131.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Thi63TTQL1_63132131Entities : DbContext
    {
        public Thi63TTQL1_63132131Entities()
            : base("name=Thi63TTQL1_63132131Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BoMon> BoMons { get; set; }
        public virtual DbSet<GiangVien> GiangViens { get; set; }
    
        public virtual int GiangVien_TimKiem(string maGV, string hoTen)
        {
            var maGVParameter = maGV != null ?
                new ObjectParameter("MaGV", maGV) :
                new ObjectParameter("MaGV", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GiangVien_TimKiem", maGVParameter, hoTenParameter);
        }
    }
}
